sonar.projectKey=yang-liquor_refactor-lab-exp1
sonar.organization=YOUR_SONARCLOUD_ORG
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml